version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: go
    ports:
      - 5432:5432  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 

  app:
    build: ./
    ports:
      - 8000:8000  
    depends_on:
      - db
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=go
      - DB_NAME=postgres
      - ADMIN_TOKEN=7rXBD1gtRblZtxyFhtEVqb6B1S1SG2dyCcbrKcOyrkSjTwIMgXoKGk0Ci7ek7FDy
      - WEBHOOK_TOKEN=buQs7IZKA5j05WuC21cgSt9DGQlqCqgrbO6EXfgWa48Lw9qkbFLRKWXKQMQMPLQb