// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package transferHandler_mock is a generated GoMock package.
package transferHandler_mock

import (
	context "context"
	transfer "go-challenge/pkg/transfer"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTransferManager is a mock of TransferManager interface.
type MockTransferManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransferManagerMockRecorder
}

// MockTransferManagerMockRecorder is the mock recorder for MockTransferManager.
type MockTransferManagerMockRecorder struct {
	mock *MockTransferManager
}

// NewMockTransferManager creates a new mock instance.
func NewMockTransferManager(ctrl *gomock.Controller) *MockTransferManager {
	mock := &MockTransferManager{ctrl: ctrl}
	mock.recorder = &MockTransferManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransferManager) EXPECT() *MockTransferManagerMockRecorder {
	return m.recorder
}

// CreateTransfer mocks base method.
func (m *MockTransferManager) CreateTransfer(ctx context.Context, transfer *transfer.Transfer) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransfer", ctx, transfer)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransfer indicates an expected call of CreateTransfer.
func (mr *MockTransferManagerMockRecorder) CreateTransfer(ctx, transfer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransfer", reflect.TypeOf((*MockTransferManager)(nil).CreateTransfer), ctx, transfer)
}

// FinishTransfer mocks base method.
func (m *MockTransferManager) FinishTransfer(ctx context.Context, id uint, status transfer.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishTransfer", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishTransfer indicates an expected call of FinishTransfer.
func (mr *MockTransferManagerMockRecorder) FinishTransfer(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishTransfer", reflect.TypeOf((*MockTransferManager)(nil).FinishTransfer), ctx, id, status)
}

// GetTransferByID mocks base method.
func (m *MockTransferManager) GetTransferByID(ctx context.Context, id uint) (*transfer.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransferByID", ctx, id)
	ret0, _ := ret[0].(*transfer.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransferByID indicates an expected call of GetTransferByID.
func (mr *MockTransferManagerMockRecorder) GetTransferByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransferByID", reflect.TypeOf((*MockTransferManager)(nil).GetTransferByID), ctx, id)
}
