// Code generated by MockGen. DO NOT EDIT.
// Source: transfer.go

// Package transfer_mocks is a generated GoMock package.
package transfer_mocks

import (
	context "context"
	transfer "go-challenge/pkg/transfer"
	user "go-challenge/pkg/user"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CreateTransfer mocks base method.
func (m *MockStorage) CreateTransfer(ctx context.Context, transfer *transfer.Transfer) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransfer", ctx, transfer)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransfer indicates an expected call of CreateTransfer.
func (mr *MockStorageMockRecorder) CreateTransfer(ctx, transfer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransfer", reflect.TypeOf((*MockStorage)(nil).CreateTransfer), ctx, transfer)
}

// GetAllPendingTransfers mocks base method.
func (m *MockStorage) GetAllPendingTransfers(ctx context.Context) ([]transfer.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPendingTransfers", ctx)
	ret0, _ := ret[0].([]transfer.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPendingTransfers indicates an expected call of GetAllPendingTransfers.
func (mr *MockStorageMockRecorder) GetAllPendingTransfers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPendingTransfers", reflect.TypeOf((*MockStorage)(nil).GetAllPendingTransfers), ctx)
}

// GetTransferByID mocks base method.
func (m *MockStorage) GetTransferByID(ctx context.Context, id uint) (*transfer.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransferByID", ctx, id)
	ret0, _ := ret[0].(*transfer.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransferByID indicates an expected call of GetTransferByID.
func (mr *MockStorageMockRecorder) GetTransferByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransferByID", reflect.TypeOf((*MockStorage)(nil).GetTransferByID), ctx, id)
}

// GetTransfersInformation mocks base method.
func (m *MockStorage) GetTransfersInformation() (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransfersInformation")
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransfersInformation indicates an expected call of GetTransfersInformation.
func (mr *MockStorageMockRecorder) GetTransfersInformation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransfersInformation", reflect.TypeOf((*MockStorage)(nil).GetTransfersInformation))
}

// GetUserByID mocks base method.
func (m *MockStorage) GetUserByID(ctx context.Context, id uint) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStorageMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStorage)(nil).GetUserByID), ctx, id)
}

// UpdateBalances mocks base method.
func (m *MockStorage) UpdateBalances(ctx context.Context, fromUserID, toUserID, amount uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalances", ctx, fromUserID, toUserID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalances indicates an expected call of UpdateBalances.
func (mr *MockStorageMockRecorder) UpdateBalances(ctx, fromUserID, toUserID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalances", reflect.TypeOf((*MockStorage)(nil).UpdateBalances), ctx, fromUserID, toUserID, amount)
}

// UpdateTransfer mocks base method.
func (m *MockStorage) UpdateTransfer(ctx context.Context, transfer *transfer.Transfer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransfer", ctx, transfer)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransfer indicates an expected call of UpdateTransfer.
func (mr *MockStorageMockRecorder) UpdateTransfer(ctx, transfer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransfer", reflect.TypeOf((*MockStorage)(nil).UpdateTransfer), ctx, transfer)
}
